version: '3'
services:
  redis-master-slave-one:
    hostname: redis-master-slave-one
    container_name: redis-master-slave-one
    build: ./6100
    volumes:
     - /data/redis-cluster/6100:/data
     - /etc/localtime:/etc/localtime
     - /etc/timezone:/etc/timezone
    ports:
     - 6100:6100
    networks:
      default:
        ipv4_address: 172.20.0.2
    restart: always
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    privileged: true
    restart: always
    
  redis-master-slave-two:
    hostname: redis-master-slave-two
    container_name: redis-master-slave-two
    build: ./6200
    volumes:
     - /data/redis-cluster/6200:/data
     - /etc/localtime:/etc/localtime
     - /etc/timezone:/etc/timezone
    ports:
     - 6200:6200
    networks:
      default:
        ipv4_address: 172.20.0.3
    restart: always
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    privileged: true
    restart: always
    
  redis-master-slave-three:
    hostname: redis-master-slave-three
    container_name: redis-master-slave-three
    build: ./6300
    volumes:
     - /data/redis-cluster/6300:/data
     - /etc/localtime:/etc/localtime
     - /etc/timezone:/etc/timezone
    ports:
     - 6300:6300
    networks:
      default:
        ipv4_address: 172.20.0.4
    restart: always
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    privileged: true
    restart: always
    
networks:
  default:
    external:
      name: redisnetwork
